name: 'Publish packages to Manticore repo'
description: 'This action publishes built packages to Manticore repo'
inputs:
  name:
    distr:
      required: true
      type: string
    arch:
      required: true
      type: string
    type:
      required: true
      type: string
    delimiter:
      required: true
      type: string
    artifact:
      required: true
      type: string
    ssh_key:
      required: true
      type: string
runs:
  using: "composite"
  steps:
    - name: Download artifact
      uses: manticoresoftware/download_artifact_with_retries@main
      with:
        name: ${{ inputs.artifact }}
        path: .
    - name: Publishing
      shell: bash
      run: |
        echo "#!/bin/sh
        echo exit_attempt
        exit 1" > script
        cat script
        ./script
      env:
        REMOTE_SERVER: root@repo.manticoresearch.com
        SSH_KEY: ${{ inputs.ssh_key }}
        SSH_KEY_LOCATION: /tmp/repo.key
        TYPE: ${{ inputs.type }}
        DELIMITER: ${{ inputs.delimiter }}
        DISTR: ${{ inputs.distr }}
