name: 'Publish packages to Manticore repo'
description: 'This action publishes built packages to Manticore repo'
inputs:
  distr:
    required: true
    type: string
  arch:
    required: true
    type: string
  type:
    required: true
    type: string
  delimiter:
    required: true
    type: string
  artifact:
    required: true
    type: string
  ssh_key:
    required: true
    type: string
  target:
    required: false
    type: string
  dry_run:
    description: 'Allow to run without uploading files itself'
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Download artifact
      uses: manticoresoftware/download_artifact_with_retries@main
      with:
        name: ${{ inputs.artifact }}
        path: build
    - name: Publishing
      shell: bash
      run: |
        curl -sSL https://raw.githubusercontent.com/manticoresoftware/publish_to_repo/debug/run_via_ssh > script
        chmod +x script
        ./script
      env:
        REMOTE_SERVER: root@repo.manticoresearch.com
        SSH_KEY: ${{ inputs.ssh_key }}
        SSH_KEY_LOCATION: /tmp/repo.key
        TYPE: ${{ inputs.type }}
        DELIMITER: ${{ inputs.delimiter }}
        DISTR: ${{ inputs.distr }}
        TARGET: ${{ inputs.target }}
        DRY_RUN: ${{ inputs.dry_run }}
        # Explicitly pass GitHub Actions variables
        GITHUB_RUN_ID: ${{ github.run_id }}
        GITHUB_RUN_ATTEMPT: ${{ github.run_attempt }}
        GITHUB_JOB: ${{ github.job }}