#!/usr/bin/env bash

echo "${SSH_KEY}" > ${SSH_KEY_LOCATION}
chmod 600 ${SSH_KEY_LOCATION}
SSH_OPTS="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
for n in `seq 1 10`; do
  TEMP_DIR=$(ssh -i ${SSH_KEY_LOCATION} ${SSH_OPTS} ${REMOTE_SERVER} "TEMP_DIR=\$(mktemp -d); if [ -z \"\$TEMP_DIR\" ]; then echo 'Failed to create temporary directory '\$TEMP_DIR >&2; exit 1; else echo \$TEMP_DIR; mkdir \$TEMP_DIR/build; fi")
  [[ $? -eq 0 ]] && break || if [[ $n -eq 10 ]]; then echo "ERROR: couldn't set TEMP_DIR" && exit 1; fi;
done

echo "Temporary directory is $TEMP_DIR"

for n in `seq 1 10`; do
  scp -i ${SSH_KEY_LOCATION} ${SSH_OPTS} -r build ${REMOTE_SERVER}:${TEMP_DIR}/
  [[ $? -eq 0 ]] && break || if [[ $n -eq 10 ]]; then echo "ERROR: couldn't scp to $REMOTE_SERVER" && exit 1; fi;
done

echo "Copied package to $TEMP_DIR"

cat <<EOF > /tmp/script
cd ${TEMP_DIR}
echo "Downloading https://raw.githubusercontent.com/manticoresoftware/publish_to_repo/main/upload_repo_${TYPE} to script"
curl -sSL "https://raw.githubusercontent.com/manticoresoftware/publish_to_repo/main/upload_repo_${TYPE}" > script
chmod +x script
echo 'Running DISTRO="${DISTR}" DIGIT_DELIMITER2="${DELIMITER}" TARGET="${TARGET}" ./script'
DISTRO="${DISTR}" DIGIT_DELIMITER2="${DELIMITER}" TARGET="${TARGET}" ./script
echo "Script finished with exit code $?"
echo "Removing ${TEMP_DIR}"
rm -rf ${TEMP_DIR}
echo "Cleaning up old temp dirs in /tmp/"
find /tmp -type d -ctime +2 -name 'tmp.*' -exec rm -rf {} \;
EOF
chmod +x /tmp/script

script_name="/tmp/script$(date +%s%3N)_$RANDOM"
for n in `seq 1 10`; do
  scp -i ${SSH_KEY_LOCATION} ${SSH_OPTS} /tmp/script ${REMOTE_SERVER}:${script_name}
  [[ $? -eq 0 ]] && break || if [[ $n -eq 10 ]]; then echo "ERROR: scp failed" && exit 1; fi;
done
echo "Copied script to ${REMOTE_SERVER}:${script_name}"

for n in `seq 1 10`; do
  ssh -i ${SSH_KEY_LOCATION} ${SSH_OPTS} ${REMOTE_SERVER} ${script_name}
  [[ $? -eq 0 ]] && break || if [[ $n -eq 10 ]]; then echo "ERROR: script failed via ssh" && exit 1; fi;
done
echo "Ran ${script_name} on ${REMOTE_SERVER}"

for n in `seq 1 10`; do
  ssh -i ${SSH_KEY_LOCATION} ${SSH_OPTS} ${REMOTE_SERVER} rm ${script_name}
  [[ $? -eq 0 ]] && break || if [[ $n -eq 10 ]]; then echo "ERROR: failed to cleanup via ssh" && exit 1; fi;
done
echo "Cleanup of ${script_name} finished"
